[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [String]$WorkItemProjDir, # Path to proj file containing test workitems generated by GenerateHelixWorkItems.ps1

    [Parameter(Mandatory = $true)]
    [String]$WorkItemProjFileNameFilter, # File name filter for work item proj files

    [Parameter(Mandatory = $true)]
    [String]$TestPayloadDir, # Path to the test binaries

    [Parameter(Mandatory = $true)]
    [String]$UploadRoot, # Logs, screenshots, etc. from the tests will be copied here so they can be uploaded.

    [Parameter(Mandatory = $true)]
    [int]$JobPositionInPhase, # JobPositionInPhase and TotalJobsInPhase determine the selection of work items to run

    [Parameter(Mandatory = $true)]
    [int]$TotalJobsInPhase,

    [int]$RerunPassesRequiredToAvoidFailure = 5,

    [switch]$EnablePackagedAppCrashDumps,

    [switch]$SkipCopyTestResultsXml
)

# This script is given a proj file generated by GenerateHelixWorkItems.ps1 containing a set of work items to execute.
# Usually these work items are executed by Helix, but in this case we are going to run them directly on the Pipeline agent
# This script is run in parallel across multiple build agents. We choose which items to run based on JobPositionInPhase/TotalJobsInPhase

$ErrorActionPreference = 'Stop'

Write-Host "WorkItemProjFile = $WorkItemProjFile"
Write-Host "WorkItemProjDir = $WorkItemProjDir"
Write-Host "TestPayloadDir = $TestPayloadDir"
Write-Host "UploadRoot = $UploadRoot"
Write-Host "JobPositionInPhase = $JobPositionInPhase"
Write-Host "TotalJobsInPhase = $TotalJobsInPhase"

if(!(Test-Path $UploadRoot))
{
    mkdir $UploadRoot
}

$dumpsDir = "C:\dumps"
if(!(Test-Path $dumpsDir))
{
    mkdir $dumpsDir
}

$dumpCollectionStartedAt = Get-Date
if($EnablePackagedAppCrashDumps)
{
    $nativeSystemDirectory = "$env:SystemRoot\System32"
    if([Environment]::Is64BitOperatingSystem -and ![Environment]::Is64BitProcess)
    {
        $nativeSystemDirectory = "$env:SystemRoot\Sysnative"
    }

    $icaclsPath = Join-Path $nativeSystemDirectory "icacls.exe"
    Write-Host "Granting AppContainer processes access to $dumpsDir"
    & $icaclsPath $dumpsDir /grant:r '*S-1-15-2-1:(OI)(CI)(M)'
    if($LASTEXITCODE -ne 0)
    {
        Throw "Failed to grant ALL APPLICATION PACKAGES access to $dumpsDir. Exit code: $LASTEXITCODE"
    }

    & $icaclsPath $dumpsDir /setintegritylevel '(OI)(CI)L'
    if($LASTEXITCODE -ne 0)
    {
        Throw "Failed to set low integrity on $dumpsDir. Exit code: $LASTEXITCODE"
    }

    & $icaclsPath $dumpsDir
    if($LASTEXITCODE -ne 0)
    {
        Throw "Failed to read permissions for $dumpsDir. Exit code: $LASTEXITCODE"
    }
}


$projFiles = Get-ChildItem -Path $WorkItemProjDir -Filter $WorkItemProjFileNameFilter

$workItems =@()
foreach($projFile in $projFiles)
{
    [xml]$content = Get-Content $projFile.FullName 
    foreach($item in @($content.Project.ItemGroup.HelixWorkItem))
    {
        if($item)
        {
            $workItems += $item
        }
    }
}

# We choose a 'slice' of work items to run based on JobPositionInPhase/TotalJobsInPhase
$workItemsToRun = @()
$i = $JobPositionInPhase - 1; # JobPositionInPhase starts at 1.
while($i -lt $workItems.Count)
{
    $workItemsToRun += $workItems[$i]
    $i += $TotalJobsInPhase
}

Write-Host "Work items to run:"
$workItemsToRun.Include
Write-Host ""

if ($workItemsToRun.Count -eq 0)
{
    Write-Host "No work items matched for this agent. Skipping test execution."
    exit 0
}

foreach($workItem in $workItemsToRun)
{
    $command = $workItem.Command
    $precommand = $workItem.PreCommands
    $workItemName = $workItem.Include
    $resultsFileName = ".\testResults-$workItemName.xml"
    $workItemUploadRoot = Join-Path $uploadRoot $workItemName
    mkdir $workItemUploadRoot

    $consoleLogOutputFile = Join-Path $workItemUploadRoot "console.log"

    $env:HELIX_CORRELATION_PAYLOAD = $TestPayloadDir
    $env:HELIX_WORKITEM_UPLOAD_ROOT = $workItemUploadRoot
    $env:rerunPassesRequiredToAvoidFailure = $RerunPassesRequiredToAvoidFailure
    $env:HELIX_DUMP_FOLDER = $dumpsDir

    Write-Host "Running $workItemName work item"

    # Due to the presence of quotes, symbols, etc. we cannot directly invoke $command from Powershell. So instead we write it to
    # a .cmd file and invoke that.
    $fullCommand = "@echo off`n$precommand`n$command"
    Write-Host $fullCommand
    Out-File -FilePath "temp-runworkitem.cmd" -Encoding ascii -InputObject $fullCommand
    try
    {
        & ./temp-runworkitem.cmd | Tee-Object -file $consoleLogOutputFile
    }
    finally
    {
        Remove-Item -LiteralPath ".\temp-runworkitem.cmd" -Force
    }

    if(!$SkipCopyTestResultsXml)
    {
        if (!(Test-Path ".\testResults.xml"))
        {
            # We expect the work item to produce a 'testResults.xml' file. If it didn't, something bad happened.
            Throw "Expected testResults.xml to be found. Something unexpected happened."
        }
    
        Move-Item .\testResults.xml $resultsFileName
    }

    Get-ChildItem -Path $workItemUploadRoot -Filter *_subresults.json | Move-Item -Destination $uploadRoot
}

# Upload at most 3 dumps from this run
$files = @(Get-ChildItem -Path $dumpsDir -Filter *.dmp -File)
if($EnablePackagedAppCrashDumps)
{
    $packageRoot = Join-Path $env:LOCALAPPDATA "Packages"
    $packageDirectories = @()
    if(Test-Path -LiteralPath $packageRoot -PathType Container)
    {
        $packageDirectories = Get-ChildItem -LiteralPath $packageRoot -Directory |
            Where-Object { $_.Name -like "XamlTAEFTests_*" }
        foreach($packageDirectory in $packageDirectories)
        {
            $files += Get-ChildItem -LiteralPath $packageDirectory.FullName -Filter *.dmp -File -Recurse -ErrorAction SilentlyContinue
        }
    }

    $diagnosticsPath = Join-Path $uploadRoot "switcher-dump-collection.txt"
    "Dump collection started at $($dumpCollectionStartedAt.ToString('o'))" |
        Out-File -LiteralPath $diagnosticsPath -Encoding utf8
    "C:\dumps permissions:" |
        Out-File -LiteralPath $diagnosticsPath -Encoding utf8 -Append
    $dumpPermissions = & $icaclsPath $dumpsDir 2>&1
    $dumpPermissionsExitCode = $LASTEXITCODE
    $dumpPermissions |
        Out-File -LiteralPath $diagnosticsPath -Encoding utf8 -Append
    "icacls.exe exit code: $dumpPermissionsExitCode" |
        Out-File -LiteralPath $diagnosticsPath -Encoding utf8 -Append
    "Native TaefHostApp WER configuration:" |
        Out-File -LiteralPath $diagnosticsPath -Encoding utf8 -Append
    $regPath = Join-Path $nativeSystemDirectory "reg.exe"
    $werConfiguration = & $regPath query "HKLM\Software\Microsoft\Windows\Windows Error Reporting\LocalDumps\taefhostapp.exe" /s 2>&1
    $werConfigurationExitCode = $LASTEXITCODE
    $werConfiguration |
        Out-File -LiteralPath $diagnosticsPath -Encoding utf8 -Append
    "reg.exe exit code: $werConfigurationExitCode" |
        Out-File -LiteralPath $diagnosticsPath -Encoding utf8 -Append
    $global:LASTEXITCODE = 0
    "Matching package directories:" |
        Out-File -LiteralPath $diagnosticsPath -Encoding utf8 -Append
    $packageDirectories.FullName |
        Out-File -LiteralPath $diagnosticsPath -Encoding utf8 -Append

    $werEvents = Get-WinEvent -FilterHashtable @{
        LogName = "Application"
        StartTime = $dumpCollectionStartedAt
    } -ErrorAction SilentlyContinue | Where-Object {
        $_.ProviderName -eq "Application Error" -or
        $_.ProviderName -eq "Windows Error Reporting"
    }
    "Application Error and WER events:" |
        Out-File -LiteralPath $diagnosticsPath -Encoding utf8 -Append
    $werEvents |
        Select-Object TimeCreated, ProviderName, Id, LevelDisplayName, Message |
        Format-List |
        Out-String |
        Out-File -LiteralPath $diagnosticsPath -Encoding utf8 -Append

    $minimumDumpWriteTime = $dumpCollectionStartedAt.AddSeconds(-5)
    $files = @($files |
        Where-Object { $_.LastWriteTime -ge $minimumDumpWriteTime } |
        Sort-Object FullName -Unique |
        Sort-Object LastWriteTime -Descending)
}

$files = @($files | Select-Object -First 3)
if($files.Count -eq 0)
{
    Write-Warning "No crash dumps were found for this test run."
}
foreach($file in $files)
{
    Write-Host "Collecting crash dump $($file.FullName)"
    Copy-Item $file.FullName $uploadRoot -Force
}
